#!/bin/bash

if [ "$ALIEN_INSTALL_TYPE" == "system" ]; then

  echo 'downloading cmake to stand in for system cmake';
  cpanm HTTP::Tiny
  af download
  mkdir -p ~/opt/cmake3
  mv cmake-*.tar.gz ~/opt/cmake3
  cd ~/opt/cmake3
  tar zxf cmake-*.tar.gz
  rm -f cmake-*.tar.gz
  mv cmake-*/* .
  rmdir cmake-*

else

  echo 'system cmake not needed';

fi
